# This Dockerfile runs API package in 'development' mode

FROM node:lts-alpine AS builder

USER node
WORKDIR /home/node/API

COPY --chown=node:node package.json lerna.json /home/node/API/
COPY --chown=node:node packages/api/package.json packages/api/tsconfig.json ./packages/api/
COPY --chown=node:node packages/api/package.json packages/api/tsconfig.build.json ./packages/api/
COPY --chown=node:node packages/shared/package.json packages/shared/tsconfig.json ./packages/shared/

RUN yarn install

COPY --chown=node:node packages/api/src ./packages/api/src/
COPY --chown=node:node packages/shared/lib ./packages/shared/lib/
RUN yarn workspace @orion/shared build

ENV NODE_ENV=development

EXPOSE 3000

CMD ["yarn", "dev"]
