name: App tests

on:
    push:
        branches:
            - main
        paths:
            - 'packages/app/**'

    pull_request:
        branches:
            - main
        paths:
            - 'packages/app/**'

jobs:
    runner-job:
        name: App test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install node
              uses: actions/setup-node@v1
              with:
                  node-version: '14'

            - name: Install dependencies
              run: yarn install

            - name: Lint code
              run: yarn lint:ci

            - name: Build App
              run: yarn workspace @orion/app build

            - name: Run App tests
              run: yarn test:app
