name: Shared lib tests

on:
    push:
        branches:
            - main
        paths:
            - 'packages/shared/**'

    pull_request:
        branches:
            - main
        paths:
            - 'packages/shared/**'

jobs:
    runner-job:
        name: Shared lib test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install node
              uses: actions/setup-node@v1
              with:
                  node-version: '14'

            - name: Install dependencies
              run: yarn install

            - name: Lint code
              run: yarn lint:ci

            - name: Build Shared Lib
              run: yarn workspace @orion/shared build

            - name: Run lib tests
              run: yarn test:shared
